name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "2.7", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        if: matrix.python-version != '2.7'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python 2
        if: matrix.python-version == '2.7'
        run: |
          sudo apt update
          sudo apt install python2 python-pip
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
          printf '1\n' | sudo update-alternatives --config python
          cd /usr/bin
          sudo ln -s /usr/bin/pip2 ./pip

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -e .

      - name: Run Tests
        run: |
          pytest vatnumber/tests.py